// packages/web-components/src/components/rds-form-field/rds-form-field.ts
import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import { classMap } from "lit/directives/class-map.js";
import { ifDefined } from "lit/directives/if-defined.js";
import stylesReset from "../../styles/stylesReset.css";
import styles from "./rds-form-field.css";
import "../rds-label/rds-label";

interface RdsFormFieldProps {
  for: string;
  label: string;
  required: boolean;
  error: boolean;
  success: boolean;
  disabled: boolean;
  helper: string;
}
@customElement("rds-form-field")
export class RdsFormField extends LitElement {
  static styles = [stylesReset, styles];

  @property({ type: String }) for: RdsFormFieldProps["for"] = "";
  @property({ type: String }) label: RdsFormFieldProps["label"] = "";
  @property({ type: Boolean }) required: RdsFormFieldProps["required"] = false;
  @property({ type: Boolean }) error: RdsFormFieldProps["error"] = false;
  @property({ type: Boolean }) success: RdsFormFieldProps["success"] = false;
  @property({ type: Boolean }) disabled: RdsFormFieldProps["disabled"] = false;
  @property({ type: String }) helper: RdsFormFieldProps["helper"] = "";

  private get classes(): Record<string, boolean> {
    return {
      "rds-form-field": true,
      "rds-form-field--error": this.error,
      "rds-form-field--success": this.success,
      "rds-form-field--disabled": this.disabled,
    };
  }

  render(): ReturnType<typeof html> {
    return html`
      <div class=${classMap(this.classes)}>
        ${this.label
          ? html`
              <rds-label
                for=${ifDefined(this.for)}
                ?disabled=${this.disabled}
                ?error=${this.error}
                ?success=${this.success}
              >
                ${this.label}
                ${this.required ? html`<span class="required">*</span>` : null}
              </rds-label>
            `
          : null}
        <slot name="input-field"></slot>
        <span class="rds-form-field__helper"> ${this.helper}</span>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "rds-form-field": RdsFormField;
  }
}

// packages/react/src/rds-form-field/RdsFormField.tsx
import React from "react";
import { createComponent } from "@lit/react";
import { RdsFormField as LitRdsFormField } from "../../../web-components";
import "../styles/styles-reset.css";
import "./rds-form-field.css";

export interface RdsFormFieldProps {
  for?: string;
  label?: string;
  required?: boolean;
  error?: boolean;
  success?: boolean;
  disabled?: boolean;
  helper?: string;
  children?: React.ReactNode;
}

const RdsFormFieldLit = createComponent({
  tagName: "rds-form-field",
  elementClass: LitRdsFormField,
  react: React,
  events: {
    onInput: "input",
  },
});

export const RdsFormField = (props: RdsFormFieldProps) => {
  const { children, ...rest } = props;

  return <RdsFormFieldLit {...rest}>{children}</RdsFormFieldLit>;
};

export default RdsFormField;
